export const PERMISSIONS = Object.freeze({
  WORKSPACE_VIEW: "workspace:view",
  WORKSPACE_UPDATE: "workspace:update",
  MEMBER_VIEW: "member:view",
  MEMBER_INVITE: "member:invite",
  MEMBER_REMOVE: "member:remove",
  MEMBER_ROLE_UPDATE: "member:role:update"
});

export const ROLE_PERMISSIONS = Object.freeze({
  OWNER: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.MEMBER_ROLE_UPDATE
  ],

  MANAGER: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_INVITE
  ],

  MEMBER: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBER_VIEW
  ],

  VIEWER: [
    PERMISSIONS.WORKSPACE_VIEW
  ]
});
export const ASSIGNABLE_ROLES = Object.freeze({
  OWNER: ["ADMIN", "MANAGER", "MEMBER", "VIEWER"],
  ADMIN: ["ADMIN", "MANAGER", "MEMBER", "VIEWER"],
  MANAGER: ["MEMBER", "VIEWER"],
  MEMBER: [],
  VIEWER: []
});